-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.d_dispositivo
(
    id_dispositivo integer NOT NULL,
    nombre_dispositivo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "nombre_SO" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre_plataforma character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "D_dispositivo_pkey" PRIMARY KEY (id_dispositivo)
);

CREATE TABLE IF NOT EXISTS public.d_items
(
    id_items integer NOT NULL,
    nombre_item character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tipo_item character varying(50) COLLATE pg_catalog."default" NOT NULL,
    categoria_item character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "D_items_pkey" PRIMARY KEY (id_items)
);

CREATE TABLE IF NOT EXISTS public.d_jugador
(
    id_jugador integer NOT NULL,
    jugador_nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    jugador_apellido character varying(50) COLLATE pg_catalog."default" NOT NULL,
    jugador_username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    jugador_genero boolean NOT NULL,
    CONSTRAINT "D_jugador_pkey" PRIMARY KEY (id_jugador)
);

CREATE TABLE IF NOT EXISTS public.d_medio_pago
(
    id_medio_pago integer NOT NULL,
    nombre_medio_pago character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "D_medio_pago_pkey" PRIMARY KEY (id_medio_pago)
);

CREATE TABLE IF NOT EXISTS public.d_moneda
(
    id_moneda integer NOT NULL,
    nombre_moneda character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "D_moneda_pkey" PRIMARY KEY (id_moneda)
);

CREATE TABLE IF NOT EXISTS public.d_pais
(
    id_pais integer NOT NULL,
    nombre_pais character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "D_pais_pkey" PRIMARY KEY (id_pais)
);

CREATE TABLE IF NOT EXISTS public.d_tiempo
(
    id_tiempo integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    CONSTRAINT "D_tiempo_pkey" PRIMARY KEY (id_tiempo)
);

CREATE TABLE IF NOT EXISTS public.h_dispositivo_fav
(
    id_dispositivo_fav integer NOT NULL,
    id_tiempo integer NOT NULL,
    id_dispositivo integer NOT NULL,
    contectados_dia integer NOT NULL,
    CONSTRAINT "H_dispositivo_fav_pkey" PRIMARY KEY (id_dispositivo_fav)
);

CREATE TABLE IF NOT EXISTS public.h_jugadores_miselaneos
(
    id_jugadores_miselaneos integer NOT NULL,
    id_tiempo integer NOT NULL,
    id_jugador integer NOT NULL,
    id_pais integer NOT NULL,
    tiempo_activo_segundos integer NOT NULL,
    id_item_fav integer NOT NULL,
    CONSTRAINT "H_jugadores_miselaneos_pkey" PRIMARY KEY (id_jugadores_miselaneos)
);

CREATE TABLE IF NOT EXISTS public.h_registros_suspensiones_miselaneos
(
    id_jugadores_miselaneos integer NOT NULL,
    id_pais integer NOT NULL,
    id_tiempo integer NOT NULL,
    registros_por_dia integer NOT NULL,
    suspensiones_cuentas_dias integer NOT NULL,
    CONSTRAINT "H_registros_suspensiones_miselaneos_pkey" PRIMARY KEY (id_jugadores_miselaneos)
);

CREATE TABLE IF NOT EXISTS public.h_ventas_fav
(
    id_ventas_fav integer NOT NULL,
    id_dispositivo integer NOT NULL,
    id_moneda integer NOT NULL,
    id_medio_pago integer NOT NULL,
    id_item integer NOT NULL,
    id_pais integer NOT NULL,
    ventas_dia integer NOT NULL,
    CONSTRAINT "H_ventas_fav_pkey" PRIMARY KEY (id_ventas_fav)
);

ALTER TABLE IF EXISTS public.h_dispositivo_fav
    ADD CONSTRAINT fk_dispositivo FOREIGN KEY (id_dispositivo)
    REFERENCES public.d_dispositivo (id_dispositivo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_dispositivo_fav
    ADD CONSTRAINT fk_tiempo FOREIGN KEY (id_tiempo)
    REFERENCES public.d_tiempo (id_tiempo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_jugadores_miselaneos
    ADD CONSTRAINT fk_dispositivo FOREIGN KEY (id_tiempo)
    REFERENCES public.d_tiempo (id_tiempo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_jugadores_miselaneos
    ADD CONSTRAINT fk_jugador FOREIGN KEY (id_jugador)
    REFERENCES public.d_jugador (id_jugador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_jugadores_miselaneos
    ADD CONSTRAINT fk_pais FOREIGN KEY (id_pais)
    REFERENCES public.d_pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_jugadores_miselaneos
    ADD FOREIGN KEY (id_item_fav)
    REFERENCES public.d_items (id_items) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_registros_suspensiones_miselaneos
    ADD CONSTRAINT fk_pais FOREIGN KEY (id_pais)
    REFERENCES public.d_pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_registros_suspensiones_miselaneos
    ADD CONSTRAINT fk_tiempo FOREIGN KEY (id_tiempo)
    REFERENCES public.d_tiempo (id_tiempo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_ventas_fav
    ADD CONSTRAINT fk_dispositivo FOREIGN KEY (id_dispositivo)
    REFERENCES public.d_dispositivo (id_dispositivo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_ventas_fav
    ADD CONSTRAINT fk_item FOREIGN KEY (id_item)
    REFERENCES public.d_items (id_items) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_ventas_fav
    ADD CONSTRAINT fk_medio_pago FOREIGN KEY (id_medio_pago)
    REFERENCES public.d_medio_pago (id_medio_pago) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_ventas_fav
    ADD CONSTRAINT fk_moneda FOREIGN KEY (id_moneda)
    REFERENCES public.d_moneda (id_moneda) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.h_ventas_fav
    ADD CONSTRAINT fk_pais FOREIGN KEY (id_pais)
    REFERENCES public.d_pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;